### ISSUE TITLE
Integração

### ISSUE THREAD

**Issue by allan1994** [allan1994/sistema_integrado_brinkids#4]
Por se tratar de uma tecnologia nova a todas as partes, é necessária que esta primeira aplicação seja uma integração forçada e compartilhada, a fim de verificar quais são as dificuldades e elencar possíveis mudanças no desenvolvimento.

**Comment by Gaobaofogo** [comment]
COlocar para quando der erro na função de autenticação enviar o 'err.status' e na rota enviar o err.status
