### ISSUE TITLE
Express - Usuários Crianças

### ISSUE THREAD

**Issue by allan1994** [allan1994/sistema_integrado_brinkids#9]
Produção de funções para tratamento de dados enviados pelo front.

**Comment by Gaobaofogo** [comment]
Necessário ajustar o caminho para onde as fotos estão sendo enviadas para bater junto com o static do express

**Comment by Gaobaofogo** [comment]
Adicionar campo 'nacionality' no schema e salvar na rota

**Comment by Gaobaofogo** [comment]
Colocar para quando deletar uma criança, deletar a foto também

**Comment by Gaobaofogo** [comment]
Deletar criança caso não consiga submeter arquivo de foto
